spring:
  application:
    name: "geo-logistics-orchestrator"
  datasource:
    url: jdbc:postgresql://localhost:5432/geologistics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: "sL8y90SuoGrepH9FXWz4sc9eQaubSbIqnGGxw6ZMHLk"
  expirationMs: 900000

cors:
  allowed-origins: "http://localhost:63342,https://myapp.com"